// restore point 2025-09-27: after PC tag format change and working MIDI manager
// This is an exact snapshot of app.js at the time of the restore.
// Do not edit this file; copy back to project root to restore.

